Repository opendevstack/ods-pipeline, pull requests merged in 2021-12, with the labels that each got.

#311 Handle test timeout in typescript task
  pkg/tasktesting/run.go
  test/tasks/ods-build-typescript_test.go
Labels: skip changelog

#321 Removing unneeded dependencies from typescript test workspace
  test/testdata/workspaces/typescript-sample-app/package-lock.json
  test/testdata/workspaces/typescript-sample-app/package.json
Labels: skip changelog

#317 Fail tests if service is unreachable
  pkg/tasktesting/check.go
  test/tasks/common_test.go
  test/tasks/ods-build-go_test.go
  test/tasks/ods-build-gradle_test.go
  test/tasks/ods-build-python_test.go
  test/tasks/ods-build-typescript_test.go
  test/tasks/ods-deploy-helm_external_test.go
  test/tasks/ods-deploy-helm_test.go
  test/tasks/ods-finish_test.go
  test/tasks/ods-package-image_test.go
  test/tasks/ods-start_test.go
Labels: skip changelog

#328 Use temp dir for sonar cmd test
  cmd/sonar/main_test.go
Labels: skip changelog

#330 Fix Helm invocation
  deploy/cd-namespace/install.sh
  deploy/central/install.sh
Labels: skip changelog

#341 Dev docs now mention explicitly set dependencies of test suites
  docs/development.adoc
Labels: documentation, skip changelog

#346 Link to build recipes in task description
  deploy/central/tasks-chart/templates/task-ods-build-go-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-go.yaml
  deploy/central/tasks-chart/templates/task-ods-build-gradle-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-gradle.yaml
  deploy/central/tasks-chart/templates/task-ods-build-python-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-python.yaml
  deploy/central/tasks-chart/templates/task-ods-build-typescript-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-typescript.yaml
  docs/tasks/ods-build-go-with-sidecar.adoc
  docs/tasks/ods-build-go.adoc
  docs/tasks/ods-build-gradle-with-sidecar.adoc
  docs/tasks/ods-build-gradle.adoc
  docs/tasks/ods-build-python-with-sidecar.adoc
  docs/tasks/ods-build-python.adoc
  docs/tasks/ods-build-typescript-with-sidecar.adoc
  docs/tasks/ods-build-typescript.adoc
Labels: documentation

#353 Reusable function to check if wanted files in test cases exist in workspace
  test/tasks/common_test.go
  test/tasks/ods-build-go_test.go
  test/tasks/ods-build-gradle_test.go
  test/tasks/ods-build-python_test.go
  test/tasks/ods-build-typescript_test.go
  test/tasks/ods-start_test.go
Labels: skip changelog

#355 introduce function to create app in sub directory
  test/tasks/common_test.go
  test/tasks/ods-build-go_test.go
  test/tasks/ods-build-python_test.go
  test/tasks/ods-build-typescript_test.go
Labels: skip changelog
