Repository opendevstack/ods-pipeline, pull requests merged in 2021-11, with the labels that each got.

#266 Simplify logs streaming code
  pkg/tasktesting/logs.go
Labels: skip changelog

#267 Expose logs in tests
  pkg/tasktesting/logs.go
  pkg/tasktesting/run.go
  test/tasks/ods-finish_test.go
  test/tasks/ods-start_test.go
  test/testdata/workspaces/empty/.gitkeep
Labels: skip changelog

#269 Various housekeeping tasks
  Makefile
  cmd/start/main.go
  cmd/start/main_test.go
  internal/gittest/repository.go
  internal/installation/bitbucket.go
  internal/installation/nexus.go
  internal/interceptor/server.go
  internal/repository/branches.go
  internal/repository/config.go
  internal/repository/config_test.go
  internal/repository/tags.go
  pkg/bitbucket/branches.go
  pkg/bitbucket/build_status.go
  pkg/bitbucket/commits.go
  pkg/bitbucket/raw.go
  pkg/bitbucket/tags.go
  pkg/bitbucket/tags_test.go
  pkg/config/ods.go
  pkg/logging/logger.go
  pkg/nexus/download.go
  pkg/pipelinectxt/context.go
  pkg/pipelinectxt/context_test.go
  pkg/tasktesting/bitbucket.go
  pkg/tasktesting/nexus.go
  test/tasks/common_test.go
  test/testdata/fixtures/bitbucket/tag-get.json
Labels: enhancement, skip changelog

#272 Artifact download binary
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  cmd/artifact-download/main.go
  cmd/artifact-download/main_test.go
  docs/accessing-artifacts.adoc
  docs/design/software-architecture.adoc
  docs/design/software-design-specification.adoc
  docs/design/software-requirements-specification.adoc
  docs/design/stakeholder-requirements.adoc
  internal/repository/config_test.go
  pkg/bitbucket/test_client.go
  pkg/nexus/test_client.go
  pkg/pipelinectxt/artifacts_test.go
Labels: enhancement

#270 Allow namespaced installation
  CHANGELOG.md
  build/package/Dockerfile.webhook-interceptor
  cmd/webhook-interceptor/main.go
  deploy/central/images-chart/templates/bc-ods-webhook-interceptor.yaml
  deploy/central/tasks-chart/templates/task-ods-build-go-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-go.yaml
  deploy/central/tasks-chart/templates/task-ods-build-gradle-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-gradle.yaml
  deploy/central/tasks-chart/templates/task-ods-build-python-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-python.yaml
  deploy/central/tasks-chart/templates/task-ods-build-typescript-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-typescript.yaml
  deploy/central/tasks-chart/templates/task-ods-deploy-helm.yaml
  deploy/central/tasks-chart/templates/task-ods-finish.yaml
  deploy/central/tasks-chart/templates/task-ods-package-image.yaml
  deploy/central/tasks-chart/templates/task-ods-start.yaml
  docs/admin-installation.adoc
  internal/interceptor/server.go
  internal/interceptor/server_test.go
Labels: enhancement

#278 moved squash to git subtree add cmd in user instruction
  .gitignore
  docs/admin-installation.adoc
  docs/introduction.adoc
  docs/user-installation.adoc
Labels: skip changelog

#298 Make task prefix customizable
  CHANGELOG.md
  cmd/sidecar-tasks/main.go
  deploy/central/tasks-chart/templates/task-ods-build-go-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-go.yaml
  deploy/central/tasks-chart/templates/task-ods-build-gradle-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-gradle.yaml
  deploy/central/tasks-chart/templates/task-ods-build-python-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-python.yaml
  deploy/central/tasks-chart/templates/task-ods-build-typescript-with-sidecar.yaml
  deploy/central/tasks-chart/templates/task-ods-build-typescript.yaml
  deploy/central/tasks-chart/templates/task-ods-deploy-helm.yaml
  deploy/central/tasks-chart/templates/task-ods-finish.yaml
  deploy/central/tasks-chart/templates/task-ods-package-image.yaml
  deploy/central/tasks-chart/templates/task-ods-start.yaml
  deploy/central/tasks-chart/values.yaml
Labels: enhancement

#300 fixed specifying image(s) to be build and pushed
  CHANGELOG.md
  scripts/build-and-push-images.sh
Labels: bug

#304 Test Helm value overwriting
  test/tasks/ods-deploy-helm_test.go
  test/testdata/workspaces/helm-app-with-dependencies/.ods/repos/database/chart/templates/deployment.yaml
  test/testdata/workspaces/helm-app-with-dependencies/.ods/repos/database/chart/values.yaml
  test/testdata/workspaces/helm-app-with-dependencies/chart/values.yaml
Labels: skip changelog

#315 added missing tests to test goal and provided install hints
  Makefile
  docs/development.adoc
  scripts/check-system.sh
Labels: documentation, good first issue, skip changelog

#292 rewrite secrets.yaml encryption/editing part
  CHANGELOG.md
  docs/user-installation.adoc
Labels: documentation

#314 Fix missing timeout flag
  Makefile
Labels: skip changelog
